# Generated by Django 2.1.5 on 2022-05-26 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('dob', models.DateField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. upto 10 digits.", regex='^\\+?1?\\d{12}$')])),
                ('aadhar', models.CharField(max_length=6, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
                ('registered_at', models.DateTimeField()),
            ],
        ),
    ]
