# Generated by Django 2.1.5 on 2022-05-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='aadhar',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
