# Generated by Django 2.1.5 on 2022-05-26 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients_App', '0002_auto_20220526_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookappointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('symptoms', models.TextField()),
                ('date_app', models.DateField(default=False)),
                ('time_app', models.CharField(max_length=40)),
                ('is_pending', models.BooleanField(default=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('doctors_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors_db')),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patients_App.patients')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.speciality_mod')),
            ],
        ),
    ]
