# Generated by Django 2.1.5 on 2022-05-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_App', '0003_bookappointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointments',
            name='dr_resp',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='bookappointments',
            name='receptionist_resp',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='bookappointments',
            name='reject_reason',
            field=models.TextField(default=None),
        ),
    ]
