# Generated by Django 2.1.5 on 2022-05-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_App', '0005_auto_20220528_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointments',
            name='reject_reason',
            field=models.TextField(default=None, null=True),
        ),
    ]
