# Generated by Django 2.1.5 on 2022-05-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients_App', '0006_auto_20220529_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('drug_allergies', models.TextField()),
                ('illnesses', models.TextField()),
                ('operations', models.TextField()),
                ('medications_history', models.TextField()),
                ('habits', models.TextField()),
                ('extrainfo', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_App.patients')),
            ],
        ),
    ]
