# Generated by Django 2.1.5 on 2022-06-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_App', '0008_auto_20220601_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointments',
            name='presciption_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
