# Generated by Django 2.1.5 on 2022-05-25 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=14)),
                ('age', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. upto 10 digits.", regex='^\\+?1?\\d{12}$')])),
                ('username', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=180)),
            ],
        ),
    ]
